name: "Repo CI] Python Code"

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2s

      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Run pre-commit
        shell: bash -l {0}
        run: |
          make init
          make pre-commit-all

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: "3.11.8"
          channels: conda-forge, defaults
